# Generated by Django 6.0.4 on 2026-05-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toponym',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID топонима')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('geometry_type', models.CharField(choices=[('Point', 'Точка'), ('LineString', 'Линия'), ('Polygon', 'Полигон')], default='Point', max_length=20, verbose_name='Тип геометрии')),
                ('geometry_coords', models.JSONField(default=dict, verbose_name='GeoJSON координаты')),
                ('center_lat', models.FloatField(blank=True, null=True, verbose_name='Широта центра')),
                ('center_lon', models.FloatField(blank=True, null=True, verbose_name='Долгота центра')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('historical_name', models.CharField(blank=True, max_length=200, verbose_name='Историческое название')),
                ('renamed_year', models.IntegerField(blank=True, null=True, verbose_name='Год переименования')),
                ('has_official_name', models.BooleanField(default=True, verbose_name='Имеет официальное название')),
                ('unofficial_names', models.JSONField(blank=True, default=list, verbose_name='Неофициальные названия (список)')),
                ('extra_info', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
            ],
            options={
                'verbose_name': 'Топоним',
                'verbose_name_plural': 'Топонимы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=50, verbose_name='Название (рус.)')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='Название (англ.)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, help_text='Emoji или CSS класс', max_length=50, verbose_name='Иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID города')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('center_lat', models.FloatField(blank=True, null=True, verbose_name='Широта центра')),
                ('center_lon', models.FloatField(blank=True, null=True, verbose_name='Долгота центра')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Код страны (ISO)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (рус.)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Название (англ.)')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Agoronym',
            fields=[
                ('toponym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agoronym', serialize=False, to='toponyms.toponym')),
                ('type_name', models.CharField(max_length=50, verbose_name='Тип (площадь, рынок...)')),
                ('square_m2', models.FloatField(blank=True, null=True, verbose_name='Площадь (м²)')),
            ],
            options={
                'verbose_name': 'Агороним',
                'verbose_name_plural': 'Агоронимы',
            },
        ),
        migrations.CreateModel(
            name='Choronym',
            fields=[
                ('toponym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='choronym', serialize=False, to='toponyms.toponym')),
                ('type_name', models.CharField(max_length=50, verbose_name='Тип (район, микрорайон...)')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Население')),
            ],
            options={
                'verbose_name': 'Хороним',
                'verbose_name_plural': 'Хоронимы',
            },
        ),
        migrations.CreateModel(
            name='Crenonym',
            fields=[
                ('toponym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='crenonym', serialize=False, to='toponyms.toponym')),
                ('type_name', models.CharField(max_length=50, verbose_name='Тип (родник, ключ...)')),
                ('flow_rate', models.FloatField(blank=True, null=True, verbose_name='Дебит (л/с)')),
            ],
            options={
                'verbose_name': 'Креноним',
                'verbose_name_plural': 'Кренонимы',
            },
        ),
        migrations.CreateModel(
            name='Hydronym',
            fields=[
                ('toponym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hydronym', serialize=False, to='toponyms.toponym')),
                ('type_name', models.CharField(max_length=50, verbose_name='Тип (река, ручей...)')),
                ('length_km', models.FloatField(blank=True, null=True, verbose_name='Длина (км)')),
            ],
            options={
                'verbose_name': 'Гидроним',
                'verbose_name_plural': 'Гидронимы',
            },
        ),
        migrations.CreateModel(
            name='Limnonim',
            fields=[
                ('toponym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='limnonim', serialize=False, to='toponyms.toponym')),
                ('type_name', models.CharField(max_length=50, verbose_name='Тип (пруд, озеро...)')),
                ('area_km2', models.FloatField(blank=True, null=True, verbose_name='Площадь (км²)')),
            ],
            options={
                'verbose_name': 'Лимноним',
                'verbose_name_plural': 'Лимнонимы',
            },
        ),
        migrations.CreateModel(
            name='Memorionim',
            fields=[
                ('toponym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='memorionim', serialize=False, to='toponyms.toponym')),
                ('type_name', models.CharField(max_length=50, verbose_name='Тип (памятник, мемориал, братская могила...)')),
                ('historical_event', models.TextField(blank=True, verbose_name='Историческое событие')),
                ('year_opened', models.IntegerField(blank=True, null=True, verbose_name='Год открытия')),
                ('architect', models.CharField(blank=True, max_length=200, verbose_name='Автор/архитектор')),
            ],
            options={
                'verbose_name': 'Меморионим',
                'verbose_name_plural': 'Меморионимы',
            },
        ),
        migrations.CreateModel(
            name='NaturalObject',
            fields=[
                ('toponym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='natural_object', serialize=False, to='toponyms.toponym')),
                ('type_name', models.CharField(max_length=50, verbose_name='Тип (парк, лес, овраг...)')),
                ('area_km2', models.FloatField(blank=True, null=True, verbose_name='Площадь (км²)')),
            ],
            options={
                'verbose_name': 'Природный объект',
                'verbose_name_plural': 'Природные объекты',
            },
        ),
        migrations.CreateModel(
            name='Urbanonym',
            fields=[
                ('toponym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='urbanonym', serialize=False, to='toponyms.toponym')),
                ('type_name', models.CharField(max_length=50, verbose_name='Тип (улица, площадь, шоссе...)')),
                ('length_km', models.FloatField(blank=True, null=True, verbose_name='Длина (км)')),
            ],
            options={
                'verbose_name': 'Урбаноним',
                'verbose_name_plural': 'Урбанонимы',
            },
        ),
        migrations.AddField(
            model_name='toponym',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toponyms', to='toponyms.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='toponym',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toponyms', to='toponyms.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='toponyms.country', verbose_name='Страна'),
        ),
        migrations.AddIndex(
            model_name='toponym',
            index=models.Index(fields=['name'], name='toponyms_to_name_47deb2_idx'),
        ),
        migrations.AddIndex(
            model_name='toponym',
            index=models.Index(fields=['category'], name='toponyms_to_categor_878181_idx'),
        ),
        migrations.AddIndex(
            model_name='toponym',
            index=models.Index(fields=['center_lat', 'center_lon'], name='toponyms_to_center__4d0433_idx'),
        ),
    ]
